### ISSUE TITLE
1.0.0.4 Social

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/MoreHitchhikers#6]
### 1.0.0.4 Social
- [ ] create/update 
  - [ ] forum post
  - [ ] CurseForge
  - [ ] SpaceDock
  - [ ] reddit post
  - [ ] Patreon post
  - [ ] promo vid (30 sec)

**Comment by staticalliam7** [comment]
Looks like it will be a kewl mod!

**Comment by zer0Kerbal** [comment]
> Looks like it will be a kewl mod!

Thank you @staticalliam7 ! It is already available - just never gave it it's own repository. Needs an update pass - after the holidays!
